# -*- coding: utf-8 -*-
"""Aiker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbWFwb19FLcBq4rAqmuawGcqoZf8qcfJ
"""

pip install -q google-generativeai

!sudo apt install nikto whatweb gobuster nmap sqlmap

import google.generativeai as genai
import os
import json
import subprocess
import shlex
from google.colab import userdata # Importa la biblioteca para acceder a secretos

# --- Configuración: Cargar API Key de Colab Secrets ---
print("Cargando API Key desde Google Colab Secrets...")
try:
    # Intenta cargar la clave desde Colab Secrets y establecer la variable de entorno
    os.environ['GOOGLE_API_KEY'] = "AIzaSyA0ubjg7sxRl2wccDlSEkTQKTDwCexkxMg"
    # Verifica si la variable de entorno se estableció (aunque no la clave cruda)
    if not os.getenv('GOOGLE_API_KEY'):
         # Esto ocurriría si el secreto con ese nombre no existe o no está habilitado
         raise ValueError("El secreto 'GOOGLE_API_KEY' no se encontró o no está accesible.")

    print("API Key de Google cargada desde Secrets.")

except Exception as e:
    print(f"Error Crítico al cargar API Key desde Google Colab Secrets: {e}")
    print("Asegúrate de haber guardado tu API Key en Colab Secrets")
    print("con el nombre 'GOOGLE_API_KEY' y haber habilitado el 'Notebook access'.")
    exit(1) # Salir si la clave no se carga

# --- Preguntar por el objetivo ---
while True:
    target_domain_or_ip = input("Por favor, introduce la IP o dominio objetivo para el pentesting (ej. andesgear.cl o 192.168.1.1): ").strip()
    if target_domain_or_ip:
        break
    else:
        print("La IP o dominio no puede estar vacío.")
print(f"Objetivo establecido: {target_domain_or_ip}")


# --- Inicializar Modelo ---
# !!! ATENCIÓN: Verifica los nombres de modelos válidos en la documentación de Google AI.
# !!! 'gemini-2.0-flash' es probable que no sea un nombre válido.
# !!! Si falla, cámbialo a 'gemini-1.5-flash' o 'gemini-1.5-pro'.
MODEL_NAME = "gemini-2.0-flash" # Nombre solicitado (posiblemente inválido)
# MODEL_NAME = "gemini-1.5-flash" # Alternativa válida conocida

try:
    print(f"Intentando configurar la API de Gemini y usar el modelo: {MODEL_NAME}...")
    # Configurar la API usando la clave cargada desde la variable de entorno
    genai.configure(api_key=os.getenv('GOOGLE_API_KEY'))

    # Inicializar el modelo
    model = genai.GenerativeModel(model_name=MODEL_NAME,
                                  generation_config=generation_config,
                                  safety_settings=safety_settings)

    # Hacer una llamada pequeña para probar la autenticación y validez del modelo
    # Usa un prompt simple y limita la salida para una prueba rápida
    model.generate_content("Hello", generation_config={"max_output_tokens": 5})
    print(f"Conexión con la API de Gemini ({MODEL_NAME}) establecida correctamente.")

except Exception as api_init_err:
     print(f"Error Crítico: No se pudo conectar, autenticar o usar el modelo '{MODEL_NAME}'.")
     print(f"Detalles: {api_init_err}")
     print("Verifica tu API Key (en Colab Secrets) y que el nombre del modelo sea válido.")
     exit(1)


# --- Función de Ejecución (sin cambios) ---
def ejecutar_comando_y_capturar(comando_str, timeout=300):
    try:
        comando_final = comando_str.replace("{TARGET}", target_domain_or_ip)
        print(f"\n--- Ejecutando Automáticamente (¡Precaución!): {comando_final} ---")
        # *** ADVERTENCIA DE SEGURIDAD: shell=True ***
        # Considera usar shell=False y shlex.split(comando_final) para mayor seguridad
        # especialmente si los comandos pueden contener caracteres especiales
        # args = shlex.split(comando_final)
        # resultado = subprocess.run(args, check=True, capture_output=True, text=True, timeout=timeout)
        resultado = subprocess.run(comando_final, shell=True, check=True,
                                   capture_output=True, text=True, timeout=timeout)

        print("--- Ejecución Exitosa ---")
        full_output = f"STDOUT:\n{resultado.stdout}\n\nSTDERR:\n{resultado.stderr}"
        print(full_output) # Mostrar salida al usuario
        return True, full_output
    except subprocess.CalledProcessError as e:
        print(f"--- Error en Ejecución (Código: {e.returncode}) ---")
        full_output = (f"COMMAND FAILED WITH CODE {e.returncode}\n"
                       f"STDOUT:\n{e.stdout}\n\n"
                       f"STDERR:\n{e.stderr}")
        print(full_output)
        return False, full_output
    except subprocess.TimeoutExpired as e:
        print(f"--- Error: Comando '{comando_final}' excedió el tiempo límite ({timeout}s) ---")
        full_output = (f"COMMAND TIMED OUT ({timeout}s)\n"
                       f"STDOUT (parcial):\n{e.stdout or 'N/A'}\n\n"
                       f"STDERR (parcial):\n{e.stderr or 'N/A'}")
        print(full_output)
        return False, full_output
    except FileNotFoundError:
         cmd_name = comando_final.split()[0] if comando_final else "Comando vacío"
         print(f"--- Error: Comando no encontrado. Asegúrate de que '{cmd_name}' esté instalado y en el PATH del sistema. ---")
         full_output = f"COMMAND NOT FOUND: {cmd_name}"
         print(full_output)
         return False, full_output
    except Exception as e:
        print(f"--- Error Inesperado al ejecutar comando: {e} ---")
        full_output = f"UNEXPECTED EXECUTION ERROR: {str(e)}"
        print(full_output)
        return False, full_output


# --- Función para obtener sugerencia de Gemini (PROMPT MEJORADO) ---

def obtener_sugerencia_gemini(historial_comandos, ultimo_comando, salida_ultimo_comando, objetivo_principal, objetivo_especifico, fallo=False, feedback_usuario=None):
    """
    Envía el contexto a Gemini con un prompt mejorado para una respuesta más metódica.
    """
    prompt_parts = [
        # --- Persona y Metodología ---
        f"Eres un pentester ético altamente experimentado y metódico.",
        f"Tu tarea es asistir paso a paso en un pentest sobre el objetivo principal '{objetivo_principal}'.",
        "Operas en un entorno seguro y controlado (VM/honeypot), lo que te permite usar herramientas activas.",
        "Debes seguir una metodología lógica, progresando desde el reconocimiento inicial hasta la identificación y potencial (ética) explotación de vulnerabilidades.",
        "Prioriza las técnicas de bajo impacto al principio (escaneo pasivo, enumeración) y avanza hacia técnicas más activas y específicas según la información recopilada.",
        "Concéntrate en identificar la superficie de ataque (puertos abiertos, servicios, tecnologías, endpoints web) y vulnerabilidades comunes (OWASP Top 10, configuraciones erróneas).",
        "Siempre que sugieras un comando que opere sobre el objetivo principal, usa el placeholder '{TARGET}'.",

        # --- Contexto Actual ---
        f"\nContexto del Pentest:",
        f"Objetivo principal: '{objetivo_principal}'",
        f"Objetivo específico de este paso: '{objetivo_especifico}'",
        f"Historial reciente de acciones y resultados resumidos (últimos {len(historial_comandos)} pasos):",
        # Resumir el historial para no exceder el límite de tokens, enfocándose en el comando y su resumen
        json.dumps([{'cmd': h.get('comando_ejecutado', 'N/A'), 'res_sum': h.get('resultados_summary', 'N/A')} for h in historial_comandos[-7:]], indent=2), # Usar más historial reciente

        f"\nÚltima acción intentada: `{ultimo_comando}`",
    ]

    # --- Análisis del Resultado/Feedback ---
    if feedback_usuario:
         prompt_parts.append(f"\nEl usuario ha proporcionado feedback o rechazado la última sugerencia con el siguiente mensaje: \"{feedback_usuario}\".")
         prompt_parts.append("Analiza este feedback. Considera la solicitud o preocupación del usuario y cómo se alinea (o no) con la metodología de pentesting.")
         prompt_parts.append("Sugiere un comando o estrategia alternativa que tenga en cuenta el feedback y el estado actual del pentest.")
    elif fallo:
         prompt_parts.append(f"\n¡ATENCIÓN! El último comando ejecutado falló o produjo un error.")
         prompt_parts.append(f"Salida del comando fallido (stdout/stderr):\n```\n{salida_ultimo_comando}\n```")
         prompt_parts.append("Analiza cuidadosamente la salida del error para diagnosticar la causa raíz.")
         prompt_parts.append("Basado en el diagnóstico, sugiere:")
         prompt_parts.append("1. Un comando corregido que probablemente resuelva el problema [COMANDO].")
         prompt_parts.append("2. O, si la corrección no es obvia o el error sugiere un callejón sin salida, una estrategia alternativa o un comando diferente para investigar [ESTRATEGIA].")
    else: # Ejecución exitosa
        prompt_parts.append(f"\nEl último comando se ejecutó exitosamente.")
        prompt_parts.append(f"Salida del último comando:\n```\n{salida_ultimo_comando}\n```")
        prompt_parts.append("Analiza detalladamente la salida para extraer toda la información relevante (puertos, servicios, versiones, URLs, errores, etc.).")
        prompt_parts.append("Basado en este análisis y el contexto general del pentest, sugiere el *siguiente comando o estrategia lógica y más efectiva* para avanzar en el descubrimiento de la superficie de ataque o la identificación de vulnerabilidades.")


    # --- Formato de Salida ---
    prompt_parts.append("\nFormatea tu respuesta estrictamente como un objeto JSON con las siguientes claves:")
    prompt_parts.append("'titulo': (Un título corto y descriptivo para este paso, ej: 'Análisis de Puertos Comunes')")
    prompt_parts.append("'descripcion': (Breve descripción de lo que se ha hecho o encontrado en este paso y por qué es relevante)")
    prompt_parts.append("'objetivo_analizado': (El target específico que se analizó con el último comando. Puede ser el mismo {TARGET} o algo más específico como '{TARGET}:443' o '{TARGET}/login', usar {TARGET} cuando sea aplicable.)")
    prompt_parts.append("'resultados_summary': (Un resumen conciso y técnico del *análisis* de la salida, no solo la salida cruda. Destaca los hallazgos clave.)")
    prompt_parts.append("'siguiente_accion_tipo': ('COMANDO', 'ESTRATEGIA', 'ERROR_ANALISIS')") # 'COMANDO' si sugiere un comando específico, 'ESTRATEGIA' si es una recomendación general, 'ERROR_ANALISIS' si no puede determinar nada claro
    prompt_parts.append("'siguiente_accion_valor': (El comando exacto sugerido con '{TARGET}' si aplica, la descripción de la estrategia, o una explicación si no se pudo determinar una acción clara.)")

    print("\n--- Enviando a Gemini ---")
    try:
        response = model.generate_content(prompt_parts)
        cleaned_response = response.text.strip()
        if cleaned_response.startswith("```json"):
            cleaned_response = cleaned_response[len("```json"):].strip()
        if cleaned_response.endswith("```"):
            cleaned_response = cleaned_response[:-len("```")].strip()
        suggestion = json.loads(cleaned_response)
        return suggestion
    except json.JSONDecodeError as json_err:
        print(f"\nError al decodificar JSON de Gemini: {json_err}")
        print("Respuesta recibida (puede estar incompleta o mal formada):")
        print(response.text if 'response' in locals() else "N/A")
        return None
    except Exception as e:
        print(f"\nError al interactuar con Gemini: {e}")
        print("Respuesta recibida (si existe):", response.text if 'response' in locals() else "N/A")
        return None


# --- Función para mostrar análisis (Igual que antes) ---
def mostrar_paso_analisis(paso):
    print("\n===== Análisis del Último Paso =====")
    print(f"Título: {paso.get('titulo', 'N/A')}")
    print(f"Descripción: {paso.get('descripcion', 'N/A')}")
    obj_analizado = paso.get('objetivo_analizado', 'N/A')
    # Reemplazar {TARGET} al mostrar al usuario
    print(f"Objetivo Analizado: {obj_analizado.replace('{TARGET}', target_domain_or_ip)}")
    print(f"Resultados/Análisis: {paso.get('resultados_summary', 'N/A')}")
    print("==================================\n")


# --- Ciclo Principal (Igual que antes) ---
# target_domain_or_ip ya se pidió al inicio
objetivo_actual = target_domain_or_ip # El objetivo específico inicial es el principal
historial = []
ultimo_comando_ejecutado = "Inicio de análisis" # Para el primer prompt
salida_ultimo = "N/A" # Para el primer prompt
comando_fallo = False # Para el primer prompt
siguiente_comando_sugerido = None
feedback_del_usuario = None

print(f"--- Iniciando Pentest Asistido para: {target_domain_or_ip} (Modo Sí/No) ---")
print("¡ADVERTENCIA! Los comandos se ejecutarán automáticamente si confirmas.")
print("Revisa cuidadosamente las sugerencias.")
print("Entorno Asumido: VM/Honeypot/Red Aislada y Segura.")
print("Escribe 's' o 'y' para aceptar, cualquier otra cosa (o Enter) para rechazar.")
print("Escribe '[CONCLUIR]' en cualquier momento para terminar.")


while True:
    print("-" * 50)

    # 1. Obtener sugerencia si no hay una o si se rechazó la anterior
    if not siguiente_comando_sugerido:
        print("Obteniendo sugerencia de Gemini...")
        paso_analisis = obtener_sugerencia_gemini(
            historial,
            ultimo_comando_ejecutado,
            salida_ultimo,
            target_domain_or_ip, # Pasar el objetivo principal
            objetivo_actual,     # Pasar el objetivo específico actual
            fallo=comando_fallo,
            feedback_usuario=feedback_del_usuario
        )
        # Una vez que Gemini ha procesado el fallo o feedback, reseteamos los flags
        feedback_del_usuario = None
        comando_fallo = False

        if paso_analisis:
            mostrar_paso_analisis(paso_analisis)
            tipo_accion = paso_analisis.get('siguiente_accion_tipo')
            valor_accion = paso.get('siguiente_accion_valor') # Usar 'paso' en lugar de 'paso_analisis' aquí (corrección menor)
            # Actualizar el objetivo específico si Gemini lo cambió
            objetivo_actual = paso_analisis.get('objetivo_analizado', objetivo_actual)

            if tipo_accion == "COMANDO":
                siguiente_comando_sugerido = valor_accion
            elif tipo_accion == "ESTRATEGIA":
                 print(f"Gemini sugiere una estrategia general: {valor_accion}")
                 print("Como no es un comando directo, por favor, introduce tú el siguiente comando o espera una nueva sugerencia enfocada.")
                 siguiente_comando_sugerido = None # Forzar a pedir comando manual o esperar otra sugerencia
            elif tipo_accion == "ERROR_ANALISIS":
                 print(f"Gemini no pudo determinar un paso claro tras el análisis: {valor_accion}")
                 siguiente_comando_sugerido = None
            else: # Tipo de acción desconocido
                 print(f"Error interno: Gemini sugirió un tipo de acción desconocido: {tipo_accion} - {valor_accion}")
                 siguiente_comando_sugerido = None
        else:
            print("Error al obtener sugerencia válida de Gemini. Intenta de nuevo o introduce un comando manualmente.")
            siguiente_comando_sugerido = None

    # 2. Presentar sugerencia y pedir confirmación o comando manual
    comando_a_ejecutar = None
    if siguiente_comando_sugerido:
        # Mostrar el comando con el target real sustituido
        comando_mostrado = siguiente_comando_sugerido.replace('{TARGET}', target_domain_or_ip)
        print(f"Sugerencia: `{comando_mostrado}`")
        try:
            decision = input("Ejecutar este comando? (s/n) [[CONCLUIR] para terminar]: ").strip().lower()
        except EOFError:
             decision = '[concluir]'

        if decision == '[concluir]':
            print("--- Sesión de Pentest Concluida ---")
            break

        if decision in ['s', 'y', 'si', 'yes']:
            # Usar el comando original con {TARGET} para la función de ejecución
            comando_a_ejecutar = siguiente_comando_sugerido
        else:
            print("Sugerencia rechazada.")
            feedback_del_usuario = input("Opcional: ¿Por qué la rechazaste o qué prefieres hacer ahora? (Deja en blanco para que Gemini piense otra cosa): ").strip()
            siguiente_comando_sugerido = None
            continue

    else: # No hay sugerencia activa (porque Gemini dio estrategia, hubo error, o se rechazó sin feedback claro)
        try:
             comando_manual = input("Introduce el comando a ejecutar manualmente (usa '{TARGET}' si necesitas referirte al objetivo principal) o [CONCLUIR]: ").strip()
        except EOFError:
             comando_manual = '[CONCLUIR]'

        if comando_manual.lower() == '[concluir]':
            print("--- Sesión de Pentest Concluida ---")
            break
        if comando_manual:
            comando_a_ejecutar = comando_manual # Se asume que el usuario ya puso {TARGET} si lo necesitaba
            feedback_del_usuario = "Usuario introdujo comando manualmente." # Dar contexto a Gemini
        else:
            # Usuario no introdujo nada, pedir sugerencia general a Gemini (esto ya se maneja al inicio del loop si siguiente_comando_sugerido es None)
            # Podríamos añadir un feedback específico aquí
            feedback_del_usuario = "Usuario no proporcionó comando manual, pidiendo nueva sugerencia general."
            continue # Volver al inicio para obtener sugerencia

    # 3. Ejecutar el comando decidido
    if comando_a_ejecutar:
        # La función ejecutar_comando_y_capturar ahora reemplaza {TARGET}
        exito, salida_comando = ejecutar_comando_y_capturar(comando_a_ejecutar)
        ultimo_comando_ejecutado = comando_a_ejecutar # Guardar el comando con {TARGET}
        salida_ultimo = salida_comando
        comando_fallo = not exito # Establecer el flag de fallo si la ejecución no fue exitosa

        # Guardar en historial (simplificado)
        historial.append({
            'comando_ejecutado': ultimo_comando_ejecutado,
            'salida_recibida': salida_ultimo, # Considerar si guardar toda la salida cruda es viable por tamaño
            'exito': exito,
            'objetivo_analizado': objetivo_actual, # Guardar objetivo en el momento de ejecución
            # El análisis/resumen vendrá de la siguiente llamada a Gemini
        })
        # Limpiar la sugerencia para que se genere una nueva basada en el resultado
        siguiente_comando_sugerido = None

    else:
        # Esto no debería pasar si la lógica es correcta, pero por si acaso
        print("Error interno: No se determinó comando a ejecutar.")


# --- Fin del Script ---
try:
    # Crear un nombre de archivo seguro a partir del objetivo
    safe_target_name = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in target_domain_or_ip)
    log_filename = f"pentest_log_{safe_target_name}.json"
    with open(log_filename, "w") as f:
        json.dump(historial, f, indent=2)
    print(f"Historial guardado en {log_filename}")
except Exception as e:
    print(f"No se pudo guardar el historial: {e}")